apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: compensationcalculator
  name: compensationcalculator
  namespace: default
spec:
  replicas: 1
  selector:
    io.kompose.service: compensationcalculator
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/compensationcalculator-default: "true"
        io.kompose.service: compensationcalculator
    spec:
      containers:
        - env:
            - name: DEV_MODE
              value: "true"
            - name: RAPID_API_KEY
              value: apikey
          image: ' '
          name: compensationcalculator
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
          resources: {}
      restartPolicy: Always
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - compensationcalculator
        from:
          kind: ImageStreamTag
          name: compensationcalculator:latest
      type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
