apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kawa-foundation-app{{.Values.namespace}} 
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.31.2 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: compensationcalculator{{.Values.environment}} 
  name: compensationcalculator{{.Values.environment}} 
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: compensationcalculator{{.Values.environment}} 
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.31.2 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/compensationcalculator-default: "true"
        io.kompose.service: compensationcalculator{{.Values.environment}} 
    spec:
      containers:
        - image: zanzibarinh/compensation-calculator:{{.Values.version}} 
          name: compensationcalculator{{.Values.environment}} 
          resources: {}
      restartPolicy: Always
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: compensationcalculator{{.Values.environment}}-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: compensationcalculator{{.Values.environment}} 
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50

